#!/bin/bash
echo "🔍 Railway MySQL Credentials"
echo "================================"
echo ""
echo "📋 Go to Railway Dashboard:"
echo "   https://railway.app/project/[your-project-id]/service/[service-id]/variables"
echo ""
echo "📝 Copy these values to DBeaver:"
echo ""
echo "Server Host: MYSQLHOST value"
echo "Port: MYSQLPORT value (usually 3306)"
echo "Database: MYSQLDATABASE value"
echo "Username: MYSQLUSER value"
echo "Password: MYSQLPASSWORD value"
echo ""
echo "================================"
