#!/bin/bash

# Simple Railway MySQL Migration Guide
# This script will show you the SQL to run manually in Railway Dashboard

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🗄️  Railway MySQL Migration - OTP System"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 OPTION 1: Via Railway Dashboard (EASIEST)"
echo ""
echo "Steps:"
echo "1. Go to: https://railway.app/dashboard"
echo "2. Click on your MySQL database service"
echo "3. Click on 'Query' tab"
echo "4. Copy the SQL below and paste it in the query editor"
echo "5. Click 'Execute'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 SQL TO RUN:"
echo ""
cat migrations/create_otp_table.sql
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 OPTION 2: Via MySQL CLI"
echo ""
echo "If you have Railway MySQL credentials, you can run:"
echo ""
echo "mysql -h <HOST> -P <PORT> -u <USER> -p<PASSWORD> <DATABASE> < migrations/create_otp_table.sql"
echo ""
echo "Get credentials from: Railway Dashboard → MySQL → Connect"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 After migration, verify with:"
echo ""
echo "SHOW TABLES LIKE 'otp_verifications';"
echo "DESCRIBE otp_verifications;"
echo "SHOW COLUMNS FROM customers LIKE 'email_verified';"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
